### ISSUE TITLE
train_meta.txt not found

### ISSUE THREAD

**Issue by MansourTrabelsi** [muhammadzaheer/car_tf#2]
Running this command `python -B main.py -t --batch_size 40 --epochs 200 --base_learning_rate=0.0001` gave me this error. Can you tell me where is that file ?  
IOError: [Errno 2] No such file or directory: '/home/mansour/roadway_intel-master/split/train_meta.txt'

Thank you for your help

**Comment by mekza** [comment]
@MansourTrabelsi try that: ```python -B main.py --setup-meta```

**Comment by MansourTrabelsi** [comment]
@mekza  I've got this error : 
`mansour@MansourPc:~/roadway_intel-master$ python -B main.py --setup-meta
/usr/local/lib/python2.7/dist-packages/pandas/core/computation/__init__.py:18: UserWarning: The installed version of numexpr 2.2.2 is not supported in pandas and will be not be used
The minimum supported version is 2.4.6
 ver=ver, min_ver=_MIN_NUMEXPR_VERSION), UserWarning)
usage: Fine tunes a VGG16 classification model on CompCars dataset
       [-h] [-t | -e] [--batch_size {20,30,40,50,60,70,80,100}]
       [--epochs EPOCHS] [--base_learning_rate {0.01,0.001,0.0001,1e-05}]
       [--decay_factor {0.1,0.01}] [--decay_epochs DECAY_EPOCHS]
       [--no_gpus {1,2}] [--setup_meta]
Fine tunes a VGG16 classification model on CompCars dataset: error: unrecognized arguments: --setup-meta`

**Comment by mekza** [comment]
@MansourTrabelsi read the source Luke! `python -B main.py --setup_meta`

**Comment by MansourTrabelsi** [comment]
@mekza Thank you for help.
`Traceback (most recent call last):
  File "main.py", line 85, in <module>
    main()
  File "main.py", line 75, in main
    settings.CHECKPOINT_DIR)
  File "/home/mansour/roadway_intel-master/roadway/vgg16/train.py", line 134, in run_training
    rd.vgg16.model.load_weights('vgg16_weights.npz', sess)
  File "/home/mansour/roadway_intel-master/roadway/vgg16/model.py", line 158, in load_weights
    weights = np.load(weight_file)
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/npyio.py", line 370, in load
    fid = open(file, "rb")
IOError: [Errno 2] No such file or directory: 'vgg16_weights.npz'`
Where can i find this file ??

**Comment by varunarathinam** [comment]
can you able resolove this issue?. im having same issue. could you please help me.
